name: Print IP Address and View Page

on:
  push:
    branches:
      - main

jobs:
  print_ip_and_view_page:
    runs-on: ubuntu-latest
    container: python:3.9-slim-buster

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        apt-get update && \
        apt-get install -y xvfb gnupg wget curl unzip --no-install-recommends && \
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
        apt-get update -y && \
        apt-get install -y google-chrome-stable && \
        CHROMEVER=$(google-chrome --product-version | grep -o "[^\.]*\.[^\.]*\.[^\.]*") && \
        DRIVERVER=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEVER") && \
        wget -q --continue -P /chromedriver "http://chromedriver.storage.googleapis.com/$DRIVERVER/chromedriver_linux64.zip" && \
        unzip /chromedriver/chromedriver* -d /chromedriver

    - name: Make Chromedriver Executable and Move to Default Selenium Path
      run: |
        chmod +x /chromedriver/chromedriver
        mv /chromedriver/chromedriver /usr/bin/chromedriver

    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -i --force-depends google-chrome-stable_current_amd64.deb
        apt-get -y install -f
        mv /usr/bin/google-chrome-stable $RUNNER_TEMP/chrome

    - name: Install pip and dependencies
      run: |
        apt-get update
        apt-get install -y python3-pip
        pip3 install -r requirements.txt
        apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        apt-get install -y tor

    - name: Start Tor Service
      run: service tor start

    - name: Configure Tor Control Port and Password
      run: |
        echo "ControlPort 9051" | tee -a /etc/tor/torrc
        echo "HashedControlPassword 16:4EA4A4B2D9CE439B59675423B71E3B2EE50F91AA5E4A508670F4D62AEC" | tee -a /etc/tor/torrc
        service tor restart

    - name: Set Tor Control Password as Environment Variable
      run: echo "TOR_PASSWORD=qwerty-pass" >> $GITHUB_ENV

    - name: Run Python Script with Tor
      run: python3 print_ip_and_view_page.py
      env:
        TOR_PASSWORD: ${{ secrets.TOR_PASSWORD }}
