name: Print IP Address and View Page

on:
  push:
    branches:
      - main

jobs:
  print_ip_and_view_page:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        apt-get update
        apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        apt-get install -y tor

    - name: Start Tor Service
      run: sudo service tor start

    - name: Configure Tor Control Port and Password
      run: |
        echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
        echo "HashedControlPassword 16:5A4B5D32EEBA8D5764B13D6CF22E598D784B6A5B87EB6F465C1AA1B21C" | sudo tee -a /etc/tor/torrc
        sudo service tor restart

    - name: Set Tor Control Password as Environment Variable
      run: echo "::set-env name=TOR_PASSWORD::qwerty-pass"

    - name: Run Python Script with Tor
      run: python print_ip_and_view_page.py
      env:
        TOR_PASSWORD: ${{ env.TOR_PASSWORD }}
