name: Print IP Address and View Page

on:
  push:
    branches:
      - main

jobs:
  print_ip_and_view_page:
    runs-on: ubuntu-latest
    container: python:3.9

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install pip and dependencies
      run: |
        apt-get update
        apt-get install -y python3-pip
        pip3 install -r requirements.txt
        apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        apt-get install -y tor

    - name: Start Tor Service
      run: sudo service tor start

    - name: Configure Tor Control Port and Password
      run: |
        echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
        echo "HashedControlPassword 16:4EA4A4B2D9CE439B59675423B71E3B2EE50F91AA5E4A508670F4D62AEC" | sudo tee -a /etc/tor/torrc
        sudo service tor restart

    - name: Set Tor Control Password as Environment Variable
      run: echo "::set-env name=TOR_PASSWORD::qwerty-pass"

    - name: Run Python Script with Tor
      run: python3 print_ip_and_view_page.py
      env:
        TOR_PASSWORD: ${{ env.TOR_PASSWORD }}
